version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
          - major

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm:
        update-types:
          - minor
          - patch
          - major
