name: 'github-actions-opentelemetry'
description: 'A GitHub Action that sends telemetry data by OpenTelemetry'
author: '35333687+paper2@users.noreply.github.com'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for client authentication'
    default: ${{ secrets.GITHUB_TOKEN }}
    required: true

runs:
  using: node20
  main: dist/index.js
