# FYI: https://containers.dev/guide/dockerfile#docker-compose
version: '3'
services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/typescript-node:20
    container_name: dev_container
    command: sleep infinity
    volumes:
      - ../..:/workspaces:cached
    networks:
      - default
  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - '9090:9090'
    command:
      - '--enable-feature=otlp-write-receiver'
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - default
  jaeger:
    image: jaegertracing/all-in-one:1.61.0
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
    networks:
      - default
networks:
  default:
    driver: bridge
