name: Send Telemetry after Other Workflow

on:
  workflow_run:
    workflows:
      - Check Transpiled JavaScript
      - Continuous Integration
      - CodeQL
      - Lint Codebase
    types:
      - completed

permissions:
  contents: read

jobs:
  test-action:
    name: Run Github Actions OpenTelemetry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run
        id: run
        uses: paper2/github-actions-opentelemetry@v0.0.2
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT:
            ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ''
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
